### ISSUE TITLE
Warlock Invocations in Optional Features?

### ISSUE THREAD

**Issue by bearndc** [kinkofer/FightClub5eXML#100]
I can't seem to find where the invocations are listed. Tje level 2 feature says the list is found in the optional features page but i haven't been able to find it. Sorry if it's a simplr answer that has flown by me.

**Comment by kinkofer** [comment]
It appears the converter I'm using might not account for the invocations. I
will update the converter and start including the invocations. It may take
a day or two, sorry for the inconvenience.

**Comment by bearndc** [comment]
No problem at all! Appreciate all the work that's put in to these.

**Comment by kinkofer** [comment]
Invocations, infusions, and maneuvers are being added as feats.
