### ISSUE TITLE
Issues I’ve found so far.

### ISSUE THREAD

**Issue by Eldarnesh** [kinkofer/FightClub5eXML#102]
Thanks in advance for the work you put into coding these files. I downloaded the latest version and apart from the missing warlock invocations I noticed that the warlock class is also missing the new pact of the talisman optional feature. I also noticed that I cannot find the artificer infusions and that the new fighting styles are not in the compendium. I know nothing about coding but I had an earlier xml which created an eldritch invocations spell class and listed all the eldritch invocations there which I found was really convenient and could probably be used to list both the invocations and infusions. Those were the issues I found, keep up the good work!

**Comment by kinkofer** [comment]
Invocations, infusions, and maneuvers are being added as feats.

Path of the Talisman and other missing features will be in the next update shortly.
