### ISSUE TITLE
Collection Lists Aren't working

### ISSUE THREAD

**Issue by Nkromancer** [kinkofer/FightClub5eXML#108]
Either I have the big dumb or there is something wrong with my version of Fight Club.  I have the entire folder of this stuff unpacked and in my phone, but when I try to import a collection it does absolutely nothing.  Please help.

**Comment by kinkofer** [comment]
If you're importing collections from this repo, you have the wrong files. 

See the instructions on the main page:
"Final XML files are released on a shared Dropbox. If you're here to import the files into your app, please refer to the instructions in the link above."

**Comment by Nkromancer** [comment]
Ok.  Thanks.  I don't use Github much, and the format it a little weird to get used to.  I will do that.

**Comment by Nkromancer** [comment]
Yep, it worked.  Thanks again for the help, and keep up the good work~
