### ISSUE TITLE
Not loading the compendium

### ISSUE THREAD

**Issue by BrandonVSC** [kinkofer/FightClub5eXML#115]
So I re-downloaded the compendiums and after unzipping them I attempted to load the full compendium. It said that the compendium loading but when I went to double check it, all of the categories were blank. No classes, no races, no monsters, nothing.

**Comment by kinkofer** [comment]
None of the compendiums require unzipping. Are you downloading from the Dropbox?

**Comment by BrandonVSC** [comment]
I am downloading from here

**Comment by zcdziura** [comment]
The compendiums found in this repository don't themselves have the data that is imported into Fight Club 5. Instead, they're just references to other source files found within this repository. You have to execute the "merge" script found within the Utilities folder here in this repo.

The instructions for doing so can be found at the end of the README.
