### ISSUE TITLE
5eTtoFC5

### ISSUE THREAD

**Issue by rogueturnip** [kinkofer/FightClub5eXML#117]
Hi!  I've been mucking around with the conversion tool.  I was wondering, what is convertbook.py for?  There is no documentation for it and I haven't been able to get it running.

**Comment by kinkofer** [comment]
You're better off contacting the owner of that repo (rrgeorge), but I think it's primarily used for the Encounter+ app. That app has the ability to show pages of text for DMs, so that script is probably taking content from adventures and source books and converting them to markdown.

**Comment by rogueturnip** [comment]
Thanks.  I'll try.  I posted an issue in the parent project but no response.
