### ISSUE TITLE
Cant import? 

### ISSUE THREAD

**Issue by Mungertron** [kinkofer/FightClub5eXML#148]
Hello all,
I’m just starting to learn this xml stuff.
When I attempt to import the complete file I get an error in fight Clive “unable to parse file. Please ensure your file format is valid”

Please help! Haha what am I doing wrong?

**Comment by dragonahcas** [comment]
Hi

Under usage it says you need to grab it from the Dropbox link
http://bit.ly/NewFCXml

**Comment by Mungertron** [comment]
Tried it from the drop box link and get the issue. When it saves to my phone or iPad it looks like it saves as a word document instead of a .xml file. 
I have other .xml files I have used but I would like to use the completed file that you all have. It’s amazing what you have complied together!
I will attach a screen shot or two of my issues
![Uploading 88B69ED0-A520-4C8D-8FF0-52DC6230EBFA.png…]()

**Comment by Mungertron** [comment]
![Uploading 1860B8C0-E2AC-42DF-8128-521CA6582239.png…]()

**Comment by Mungertron** [comment]
Not sure if the import is working for the pictures 😓

**Comment by dragonahcas** [comment]
I had to open it from Dropbox app then export then save to files when I use
iPad. I would Recommend downloading via a PC and then emailing the xml to
yourself if possible.

**Comment by Mungertron** [comment]
Awesome I will give that a shot when I get home. *fingers crossed*

**Comment by nardbagel** [comment]
I am having issues importing the complete xml file as well. I downloaded straight from dropbox to my device and it just says "unable to load file"

**Comment by MightyAtom82** [comment]
Hi guys, having the same issue. Also the dropbox link is broken for me as well. Is there an updated link?

**Comment by almightychito** [comment]
yeah that's weird a couple of weeks ago it was working fine maybe the devs are updating it because of the new book.
