### ISSUE TITLE
Dropbox no longer up

### ISSUE THREAD

**Issue by Kuiriel** [kinkofer/FightClub5eXML#157]
http://bit.ly/NewFCXml no longer works. Dropbox appears to have an issue and the page redirects to an error instead.

**Comment by dragonahcas** [comment]
Dropbox shut my account down for copyright infringement.

**Comment by Kuiriel** [comment]
There are private groups on Facebook that share all sorts of content made by folk to share locally, item cards etc. Perhaps a privately joined group for sharing of compiled xml files might be more appropriate.

**Comment by dragonahcas** [comment]
If you want to look up EncounterPlus on iOS and go to their discord and ask about files someone might be able to help. The people who were helping me with this mostly work on encounterplus now (which files are compatible with Fight Club.) I'm no longer on this project anymore due to personal reasons. 

https://encounter.plus/

https://www.reddit.com/r/EncounterPlus/

**Comment by esabol** [comment]
> I'm no longer on this project anymore due to personal reasons.

I'm sorry to hear that. Is anyone still at the helm here, like @kinkofer ?

**Comment by Paladin0997** [comment]
I am trying to figure out how to download all of this I am getting confused, I tried googling a couple of things but it does not seem to help, the drop box link goes to an error page, and when I try to view the raw xml file it goes to a blank page, I don’t know what I am doing wrong

**Comment by kinkofer** [comment]
With the Dropbox down, you’ll have to follow the instructions for creating a compendium and merging the files into an xml file you can import into FightClub. 
I’ll eventually work on a different form of distribution.

**Comment by asenci** [comment]
Have you thought of using Github releases? Should be relatively straightforward to create a github action to build the XML and create a release with the artefact...

**Comment by kinkofer** [comment]
I could possibly use Github releases for the full compendium, but my goal has been to allow people to customize their sources, especially for players. To that end, I've been working on a [site](https://dnd.kinkofer.com), but it's a bit behind and I'm wary of announcing it too publicly.

**Comment by ebullient** [comment]
customizing the sources is _great_. I wrote a whole little app to convert FC XML to markdown so I can get (another) view of my curated sources.

**Comment by ebullient** [comment]
if it helps, I have a script in a branch of my fork that might explain? https://github.com/ebullient/FightClub5eXML/blob/ddice-uvms/build.sh
