### ISSUE TITLE
Travis CI not working

### ISSUE THREAD

**Issue by esabol** [kinkofer/FightClub5eXML#161]
The latest `dropbox-deployment` gem requires a version of the `faraday` gem that only works on Ruby 2.4+.

Changing
```
    - rvm install 2.3.8
```
to
```
    - rvm install 2.4.5
```
in the `.travis.yml` file will get the checks working again with PRs.

However, in light of issue #157, maybe the `dropbox-deployment` stuff should all be commented out or removed?

**Comment by esabol** [comment]
The “**Travis CI - Branch** _Expected — Waiting for status to be reported_” message should be fixed by following the **Remedy** instructions found here:

https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

**Comment by esabol** [comment]
Ping @kinkofer

**Comment by kinkofer** [comment]
Removed Dropbox deployment in #168.
