### ISSUE TITLE
EGtW Spells Issue

### ISSUE THREAD

**Issue by hsrco** [kinkofer/FightClub5eXML#164]
I'm attempting to import the spells file for the Explorer's Guide to Wildemount, but I'm getting an error: 

Error 
Unable to parse file. Please verify that your file format is valid. XML ERROR: 
The operation couldn't be completed. (NSXMLParserErrorDomain error 41.) 
(Line: 88, Column: 90)

I looked over line 88 of the file, and couldn't see anything wrong with it, but I'm not exactly well versed with these kinds of files. If anyone could help us with this, I'd super appreciate it!

**Comment by esabol** [comment]
Did you follow the instructions in the README.md to build your own compendium file, @hsrco ?

I don't think you can import just a single XML file...
