### ISSUE TITLE
Error when trying to import xml files

### ISSUE THREAD

**Issue by ctme2000** [kinkofer/FightClub5eXML#183]
Hi,

Tried importing an xml file (complete.xml) into fightclub and it errors out (screenshot attached):
![Screenshot_20220217-093959_Fight Club 5](https://user-images.githubusercontent.com/99897222/154517944-12fa3ee0-6d6f-495f-b9cf-6205ea5bd981.jpg)

**Comment by zcdziura** [comment]
That's because what you imported wasn't a proper compendium, as what Fight Club 5e expects. You instead tried to import a template that's used to build a compendium.

See the following discussion for some instructions:
https://github.com/kinkofer/FightClub5eXML/discussions/170
