### ISSUE TITLE
Game Master 5 Compatibility

### ISSUE THREAD

**Issue by Simbathecat** [kinkofer/FightClub5eXML#187]
First of all, you are amazing; thank you for your service. I initially could not get the collection file to sync to Fight Club 5, but after using your website as linked in a previous issue (https://dnd.kinkofer.com/) this was resolved. I am so grateful for your hard work in keeping this resource useable. I am just wondering if the files are compatible with the Game Master app; or if they only work with the Fight Club 5 app. Thank you for your time.

**Comment by kinkofer** [comment]
Yes, these are also compatible with Game Master, it shares the same xml
format.
