### ISSUE TITLE
Warlock xml misses autolevel slots

### ISSUE THREAD

**Issue by shnaps** [kinkofer/FightClub5eXML#191]
I've checked and warlock misses autolevel slots for skills. It goes 2,-,-,etc, only leveling up cantrips.

**Comment by Bloodis94** [comment]
If someone wants to fix this issue, i've created a [pull request](https://github.com/ogre-project/FightClub5eXML/pull/6) on the ogre-project fork of this repository

**Comment by abc** [comment]
Thanks for reporting - thanks to @Bloodis94 this has been fixed in [the ogre-project fork](https://github.com/ogre-project/FightClub5eXML) of this project.
