### ISSUE TITLE
Spell info is being overwritten

### ISSUE THREAD

**Issue by pc329** [kinkofer/FightClub5eXML#44]
In the Complete.xml file some spells have all their info removed except the name. They are in the file twice, one has all the info and the other one that overwrites is blank. They showed up as cantrips in the app, its how I noticed.

the ones I found were:
Animate dead
Elemental weapon
Heroes’ Feast
Rary’s Telepathic Bond (Ritual Only)
Tenser’s Transformation

**Comment by kinkofer** [comment]
Thanks for pointing this out. The spell names didn't match exactly so they weren't being merged correctly. This is fixed in #46 and will be released today.

**Comment by pc329** [comment]
The bottom 3 on my list above are still being overwritten. using the 2/19/2020 Complete.xml

**Comment by dragonahcas** [comment]
@pc329 Make sure you delete compendium and re-add, I do not have the same issue.
