### ISSUE TITLE
Bag of Beans typo

### ISSUE THREAD

**Issue by FriendlyNPC** [kinkofer/FightClub5eXML#50]
CoreRulebooks.xml > Wonderous Items > Bag of Beans

> 5d4 toadstools sprout. If a creature eats a toadstool, roll any die. On an odd roll, the eater must succeed on a DC 15 Constitution saving throw or take **_Sd6 poison damage_** and become poisoned for 1 hour. On an even roll, the eater gains 5d6 temporary hit points for 1 hour. 

Sd6 should be 5d6

**Comment by dragonahcas** [comment]
Thanks for this. I have already have a large task of going through the XML and fixing all issues like this in the future so will update this at the same time.

**Comment by kinkofer** [comment]
We should leave open until it’s fixed so others don’t open the same issue.
Once you start working on an issue you can assign it to yourself so we don’t have multiple people working on it at once. 
Then once the pull request is submitted you can link it to the issue and it will automatically be closed once the pull request is merged.
