### ISSUE TITLE
Missing Artificer Infusions

### ISSUE THREAD

**Issue by kinkofer** [kinkofer/FightClub5eXML#52]
Looks like Artificer Infusions were never added. Need to add for ERftLW and UA 2020 Subclasses Part 3.

**Comment by MrFarland** [comment]
I have these done as spells, but I left them on my laptop at work. I can
shoot em your way on Monday.

**Comment by kinkofer** [comment]
That'd be great, thanks. Luckily I haven't heard any complaints about it yet.

**Comment by MrFarland** [comment]
[artificer-infusions.zip](https://github.com/kinkofer/FightClub5eXML/files/4275037/artificer-infusions.zip)

**Comment by kinkofer** [comment]
@MrFarland, FYI "Infusion: Replicate Magic Item" is missing its name in your xml.
