### ISSUE TITLE
Wizard leveling table

### ISSUE THREAD

**Issue by sleepyjoe12** [kinkofer/FightClub5eXML#55]
Some info about the number of cantrips a wizard should know is written wrong. From 4th-9th levels, they should know at least 4 cantrips. However, the compendium as written lists wizards only have 3 cantrips known from 5th to 9th level.

**Comment by dragonahcas** [comment]
Thanks will amend. It's correct at 4th level but then drops down to 3 cantrips at level 5 in the table

**Comment by dragonahcas** [comment]
Looks like it's always been wrong from the original files I worked off of so will update.
