### ISSUE TITLE
Missing creatures from Mad Mage

### ISSUE THREAD

**Issue by TheTrueWizard** [kinkofer/FightClub5eXML#60]
Some creatures from the adventure module “Waterdeep - Dungeon of the Mad Mage” appear to be missing.

Halaster Blackcoat p310
living unseen servant p313
Muiral p314
scaladar p315
shadow Assassin p316
were bat p317

Thank you so much for taking the time to make these compendiums complete.

**Comment by kinkofer** [comment]
Scaladar and Werebat should be there already, but I've added the others.

**Comment by kinkofer** [comment]
Will be fixed in #67
