### ISSUE TITLE
Please create a new tutorial for installing the files

### ISSUE THREAD

**Issue by Sirroe** [kinkofer/FightClub5eXML#80]
I can see that there was a lot of work put into these files. Especially since it's being updated till now.
I've downloaded all of it and tried importing the collection .xmls but it doesn't work. Either the files are broken (unlikely) or I'm doing something wrong (more likely). 

I'm pretty sure this is the wrong place to put this up but I have no idea where else to post it.

**Comment by cjennewein-uhi** [comment]
The "Usage" section of this repo explains you will not find the files to import directly into an app. We want to keep the sources available but not draw any unwanted attention. You will either need to build the compendium (follow the remaining instructions) or find somewhere they're hosted (search online).

**Comment by kinkofer** [comment]
The "Usage" section of this repo explains you will not find the files to import directly into an app. We want to keep the sources available but not draw any unwanted attention. You will either need to build the compendium (follow the remaining instructions) or find somewhere they're hosted (search online).
