### ISSUE TITLE
Any plans to include the new Exploring Eberron book?

### ISSUE THREAD

**Issue by davidherrold** [kinkofer/FightClub5eXML#82]
Exploring Eberron looks like it includes a bunch of new sub-races, sub-classes, racial feats, etc. Are there any plans to include that new book? Thanks

**Comment by dragonahcas** [comment]
Big changes coming. We're working with some other creators to bring one compendium with updated and more consistent xml formatting for faster updating. This book will most likely be added if it's an official release.
