### ISSUE TITLE
xml vs 5etools json

### ISSUE THREAD

**Issue by rogueturnip** [kinkofer/FightClub5eXML#93]
Hi there!  I was just curious how close is the fight club 5e xml to the 5etools json?  Wanted to know so that if I'm using both sources should I expect some differences?

**Comment by kinkofer** [comment]
I'm currently transitioning so that all the data is converted from 5eTools, so in about a month it will all come from there.

**Comment by rogueturnip** [comment]
That's excellent!  Will you be releasing the conversion tool open source?

**Comment by kinkofer** [comment]
I've forked this repo to make some modifications for my preferred format, but otherwise pretty solid tool on its own:
https://github.com/rrgeorge/5eTtoFC5

**Comment by rogueturnip** [comment]
Very nice!  Thanks.  I played with the JSON myself but it's a very complex format, especially the entries part.

**Comment by kinkofer** [comment]
If you need any help feel free to reach out again.

**Comment by rogueturnip** [comment]
Thanks!

**Comment by rogueturnip** [comment]
I know this is a closed ticket but didn't want to open another for it.  In the conversion tools what is the convertbook.py suppose to do? I was trying to get it to work but it was failing on me and the readme doesn't document use.

**Comment by kinkofer** [comment]
You're better off contacting the owner of that repo, but I think it's
primarily used for the Encounter+ app. That app has the ability to show
pages of text for DMs, so that script is probably taking content from
adventures and source books and converting them to markdown.
