### ISSUE TITLE
CoreOnly in Dropbox missing Leather Armor and other basics

### ISSUE THREAD

**Issue by fffergal** [kinkofer/FightClub5eXML#95]
Hello,

2 weeks ago I download files from Dropbox and CoreOnly had everything I was expecting. Some friends tried it now, and I checked too, and the version in Dropbox is missing basics like Leather Armor when imported into Fight Club 5e.

Let me know if there's anything I can do to help you reproduce it.

Thanks,

Fergal

**Comment by kinkofer** [comment]
This will be corrected in the next update coming soon, hopefully today or tomorrow at the latest.

**Comment by fffergal** [comment]
Sounds great, thanks @kinkofer. And thanks for the project in general 🙂
