### ISSUE TITLE
CoreRulebooksAndSupplements.xml TCE Ranger

### ISSUE THREAD

**Issue by steve3d34** [kinkofer/FightClub5eXML#97]
The new content for rangers (favoured foe, deft explorer, new subclasses ect) from TCE doesn’t load when using only CoreRulebooksAndSupplements.xml

**Comment by quantized-omega** [comment]
Are the TCE stuff added in the collections already? The Readme file has not been changed yet, so I guess they might not be?

**Comment by kinkofer** [comment]
It has been added but because it’s so new we’re making more changes and fixes each day.
